server:
  port: 8000
  servlet:
    context-path: /blog
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/SpringbootTest?serverTimezone=Asia/Seoul
    username: root
    password: 0925

  jpa:
    generate-ddl: true
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        #Entity(= table)? ??? ?? ? ??? field? ??????? ?
        #?? ????? SpringPhysicalNamingStrategy? ??.
        #?? ?? ?? ex) myEamil -> my_email ??? ??
      use-naw-id-generator-mappings: false #jpa? ?? ??? ??? ???? ???
    show-sql: false #???? ???
    properties:
      hibernate.format_sql: true

  jackson:
    serialization:
      fail-on-empty-beans: false